### PR TITLE
Add Traefik v2 and Xteve enhanced app

### PR DESCRIPTION
**Pull request by MickyGX**

### CODE REVIEW

**Comment by SConaway** [comment]
Any chance this could get merged?

**Comment by KodeStar** [comment]
Fix the conflicting files and I'll look at merging, sorry it's taken so long to look at this

**Comment by lexfrei** [comment]
@SConaway, do you need any assistance with fixing conflicts?

**Comment by SConaway** [comment]
Hi @lexfrei!

 I am not the original opener of this PR. However, I can copy it and make any needed changes there if it would get merged. Let me know. Thanks!

**Comment by lexfrei** [comment]
Oops, wrong mention.
Cc @MickyGX

**Comment by SConaway** [comment]
no worries.

**Comment by SConaway** [comment]
No worries. Is this PR likely to get merged soon?

**Pull request closed without merging**
