### PR TITLE
Add RasperryMatic/CCU3 Foundation App

### PR DESCRIPTION
**Pull request by TWIX99b**

### CODE REVIEW

**Comment by keriati** [comment]
Please add the logo image file to the PR.

**Comment by Mac852** [comment]
2 logo files

rasperrymaticccu3

rasperrymaticccu3

**Review by mvdkleijn — CHANGES_REQUESTED** [review]
Hi there @TWIX99b , new maintainer working through a backlog of old PRs. Hoping you still want to update this PR.

If you could, please update this PR with the following:
- Name in app.json should equal directory name and class name;
- Icon is missing. @Rygle kindly looked up one and added it as a comment to the PR, but I need it *in* the PR as an added file.

Make sure to check https://github.com/linuxserver/Heimdall-Apps/wiki/Image-requirements for image requirements. Two most important ones:
- 256x256
- for PNGs: run through tinypng.com

**Comment by mvdkleijn** [comment]
As this is from pre-2023 and no replies were made since my initial comment, I'm closing this under the assumption this will no longer be worked on. Feel free to leave a comment so we can re-open the PR if needed.

**Pull request closed without merging**
