### PR TITLE
Add Fortigate foundation app

### PR DESCRIPTION
**Pull request by ValiEne**
Added Fortigate foundation app

### CODE REVIEW

**Comment by Argevollen** [comment]
@ValiEne missing icon file

**Review by Argevollen — CHANGES_REQUESTED** [review]
missing icon file

**Review by Argevollen — APPROVED** [review]

**Review by mvdkleijn — CHANGES_REQUESTED** [review]
Icon file is missing. An icon file is required. Please see:

- https://github.com/linuxserver/Heimdall-Apps/wiki/Submitting-an-app
- https://github.com/linuxserver/Heimdall-Apps/wiki/Image-requirements

**Comment by mvdkleijn** [comment]
I'm assuming here that Fortigate != FortiMonitor?

https://github.com/linuxserver/Heimdall-Apps/tree/master/FortinetFortiMonitor

**Comment by mvdkleijn** [comment]
- no reaction is last month
- no icon

closing, feel free to reopen / comment when desired

**Pull request closed without merging**
