### PR TITLE
Add jdownloader-enhanced-app

### PR DESCRIPTION
**Pull request by Subtixx**
Adds Speed and status to the card of jdownloader:

grafik

### CODE REVIEW

**Comment by KodeStar** [comment]
This is way more in depth than I can go through at this time of night, I'll try to look at it tomorrow, through from a quick look why is it using:
```
class MYJDAPI
```
Rather than
```
class JDownloader extends \App\SupportedApps implements \App\EnhancedApps {
```

**Comment by Subtixx** [comment]
MYJDAPI is a support class to support the API of JDownloader, if needed to I can implement the JDApi inside the JDownloader class, however I found it more readable to have it a seperate class

**Comment by bin101** [comment]
@Subtixx @KodeStar This is sitting here since 9 month already. Would love if this get merged :)

**Comment by Subtixx** [comment]
🤷 i've waited for an answer if he wanted me to implement the class inside the JDownloader class for over a year now, tbh I've forgotten about it since I run my own local copy with all my changes implemented.

**Comment by mvdkleijn** [comment]
I'm running through old PRs in the hopes of reducing the list of outstanding PRs to zero @Subtixx . I realize it's been some time, if you're still willing to update this PR to get it in please let me know.

Also, I personally don't see a particular problem with the way you did it.

**Review by mvdkleijn — CHANGES_REQUESTED** [review]
If you're still willing to update the PR, please update it against latest master. Thanks.

**Comment by mvdkleijn** [comment]
As this is from pre-2023 and no replies were made since my initial comment, I'm closing this under the assumption this will no longer be worked on. Feel free to leave a comment so we can re-open the PR if needed.

**Pull request closed without merging**
