### PR TITLE
Add ViMbAdmin App

### PR DESCRIPTION
**Pull request by HendrikF**

### CODE REVIEW

**Comment by KodeStar** [comment]
Icons should be pngs or svgs and preferably square

**Comment by HendrikF** [comment]
Updated

Its pretty hard to find square logos for some projects, and I am not that experienced to make one.

**Comment by KodeStar** [comment]
Yeah, understood, the issue is long logos are really hard to see, if you look at http://apps.heimdall.site/request/list#5f0180fbeccdee64f7314b367e87e6994089f199 the text is barely legible and repeated by the app name anyway.
Also you updated the file, but didn't update the json, so it's not pointing to the correct name anymore. The point of using a png was to have a transparent background.
All that said, this project doesn't seem to have any decent images or currently be active, so short of someone generating one I guess it's the best we're going to get for now.
Put the jpg back up and make sure the names match and I'll approve it.

**Comment by HendrikF** [comment]
Yeah, seems like I forgot the app.json file.

I just removed that commit again.

**Pull request merged**
