### PR TITLE
added dizquetv

### PR DESCRIPTION
**Pull request by HWienhold**

### CODE REVIEW

**Comment by mvdkleijn** [comment]
Thanks for the contribution. There was a single PHPCS error during the checks. Please correct that issue, otherwise all looking good.

**Comment by HWienhold** [comment]
so ideally 
Pascal case = class name = namespace = name = the way the app name is actually written ? not sure how that works

**Comment by mvdkleijn** [comment]
See one of the other apps (for example adguardhome) in this repo as an example.

**Comment by HWienhold** [comment]
Didnt you mean something like phpMyAdmin? bc AdGuard Home is Pascal case. So: shall ich revert to the first commit and add:
`// phpcs:ignore` then?

**Comment by mvdkleijn** [comment]
The app's directory name, classname, etc should all be PascalCase, like for AdguardHome.

But since you closed this PR, the question is no longer relevant.

**Pull request closed without merging**
