### PR TITLE
Enhanced mailcow

### PR DESCRIPTION
**Pull request by PedroBuffon**
Now the app shows number of Mailboxes/Domains and queue in the dashboard.

### CODE REVIEW

**Comment by mvdkleijn** [comment]
Some php codesniffer errors, mostly whitespace

**Comment by PedroBuffon** [comment]
It`s vs code, when i press enter it automatically adds a tab to the line hehehe, i updated the code and removed the whitespaces

**Comment by mvdkleijn** [comment]
You'll have to resolve the merge conflict.... due to gotify being changed here as well.

**Comment by PedroBuffon** [comment]
idk why it keeps having errors, i reseted the gotify app on the branch.

**Pull request merged**
