### PR TITLE
add passbook

### PR DESCRIPTION
**Pull request by juancv**

### CODE REVIEW

**Review by mvdkleijn — CHANGES_REQUESTED** [review]
What's the enhanced part of this app? I'm pretty sure passbolt doesn't have a queue or speed to show in the enhanched section.

Shouldn't this be a foundation app instead?

**Comment by mvdkleijn** [comment]
Also, it doesn't have an icon. Please see the wiki for details on the icon. An icon is required.

**Comment by mvdkleijn** [comment]
Lastly, the passbolt files don't pass the codesniffer tests.

This implies to me that you copied old code from somewhere instead of using the developer template. New PRs using the dev templates should pass the codesniffer checks.

Specifically see the code sniffer results in the failed tests.

**Comment by listiges-kaenguru** [comment]
Added the foundation app in PR #702

**Comment by mvdkleijn** [comment]
Closing this in favor of #702
No offense @juancv :smile:

**Pull request closed without merging**
