### PR TITLE
Add Zabbix

### PR DESCRIPTION
**Pull request by dgibbs64**

### CODE REVIEW

**Comment by dgibbs64** [comment]
Sadly there is no official square logo available. I could, however, make it square if that would work?

https://www.zabbix.com/logo

**Comment by KodeStar** [comment]
something more like this maybe? https://i1.wp.com/www.techrunnr.com/wp-content/uploads/2018/09/zabbix-logo.png?zoom=2&resize=300%2C300&ssl=1

**Comment by dgibbs64** [comment]
@KodeStar I am unsure if that is an official logo or not. Zabbix advises against altering the logo. I will try to reach out to them to ask if they have an official square logo available or would be happy with an alternative.

**Comment by KodeStar** [comment]
Did you ever hear back off them?

**Comment by dgibbs64** [comment]
Sorry other commitments have got in the way. I will ask them as soon as I get a little free time :)

**Comment by dgibbs64** [comment]
FYI Zabbix employee. Two logos suggested.

zabbix

zabbix-logo

**Comment by KodeStar** [comment]
Either work for me

**Comment by dgibbs64** [comment]
I have been in contact with them. Was just didn't get the chance to email them last night. :)

**Pull request merged**
