### PR TITLE
Add Immich Enhanced app

### PR DESCRIPTION
**Pull request by sidevesh**
Trying to add Enhanced app for Immich and I think this implementation would work but I can't test it out locally for the life of me.
I have added / upgraded enhanced apps before and this time I just can't get things to work.

```
I am running heimdall in docker and updating files `/config/www/SupportedApps/Immich` does not show updated options when adding Immich app on dashboard,
restarting container after the change did nothing.
`php artisan register:app --remove Immich` and then `php artisan register:app Immich` does nothing, restarting container after this does nothing.

I have tried following https://github.com/linuxserver/Heimdall-Apps/wiki/Creating-Enhanced-Apps and nothing.

I don't remember this being so confusing before, what am I missing ?
```
Edit: Got things working locally and resolved issues, this should be good to merge now.
Screenshot 2024-02-06 at 10 51 37 AM

I had to edit `/app/www/storage/app/supportedapps.json` to get updated app.json properties to reflect.
Got the idea when I saw https://github.com/linuxserver/Heimdall/pull/1246

### CODE REVIEW

**Comment by mvdkleijn** [comment]
Nothing changed on that front as far as I'm aware. You made sure your browser isn't caching anything?

I'll try to look at it later today but no promises.

**Comment by sidevesh** [comment]
I dont see any caching, I see the `appload` api call when I select Immich when creating app and even after registering the app it returns enhanced as false, the description change does not show up either.

**Comment by sidevesh** [comment]
also the it seems like the files in `/app/SupportedApps/folder` which I assume is `/app/www/app/SupportedApps/folder` keep resetting somehow, I update the php file and after a while it goes back to foundation app state.
Any new files, config.blade.php and livestats.blade.php remain though.
Really not sure what's happening.

I can confirm that after updating the files in both `/app/www/app/SupportedApps/Immich` and `/config/www//SupportedApps/Immich` and `register:app --remove` and `register:app`,
the appload response still remain unupdated with enhanced false and the description changes not showing up.

**Comment by sidevesh** [comment]
@mvdkleijn I got the issue of not being able to test things locally fixed,
have mentioned in Edit about the process that took,
but anyways, I have tested these changes now and this is good to go now.

**Comment by mvdkleijn** [comment]
@sidevesh Not sure why you'd need to edit supportedapps... should not be necessary I believe.

**Pull request merged**
