### PR TITLE
Add Zwavejs2Mqtt

### PR DESCRIPTION
**Pull request by Dallas-J**

### CODE REVIEW

**Comment by dgibbs64** [comment]
missing logo

**Comment by Dallas-J** [comment]
Updated with logo, let me know if you think it displays poorly and I can edit it.

**Comment by mvdkleijn** [comment]
Hey @Dallas-J I'm a new contributor working through old PRs. Yours is *almost* good to go. Could you update the PR by renaming the directory to "Zwavejs2Mqtt" please?

**Review by mvdkleijn — CHANGES_REQUESTED** [review]
Fixed some stuff myself, you just need to update the directory name.

**Comment by Dallas-J** [comment]
Done, thanks for working through the backlog here!

**Comment by mvdkleijn** [comment]
LGTM. Merging. Some linter errors but I need to update that dufus check anyways.

**Pull request merged**
