### PR TITLE
Fluidd

### PR DESCRIPTION
**Pull request by HoneyBearTech**
Added Fluidd foundation app

### CODE REVIEW

**Comment by hasecilu** [comment]
Are these the changes proposed on #644 ?

**Comment by MrLaFitte** [comment]
> Are these the changes proposed on #644 ?

No, but it is similar. I'd choose this one in favor of #644, as this one is enhanced.

**Comment by Argevollen** [comment]
> > Are these the changes proposed on #644 ?
> 
> No, but it is similar. I'd choose this one in favor of #644, as this one is enhanced.

Sorry for my english (G.translate)

I don't see how he is better. Due to the fact that it supposedly has support for advanced settings, which doesn’t work (I couldn’t find that there was an API in Fluidd)? And, as far as I can see, the files with advanced capabilities are those that are generated by default....

**Comment by MrLaFitte** [comment]
You're right, this is just using the default enhancement files. It provides no improvement over #644 

However, they both can easily be enhanced by using similar config from #642, as they both use the Moonraker API.

**Comment by mvdkleijn** [comment]
Hey there, new extra maintainer here... as you may -or may not- have noticed, I'm working through the backlog of old issues and PRs.

I've seen this one and some other (related?) PRs. I haven't had time to grok the relationships and what the best way forward is, but I just wanted to let you know I'll get to this one soon-ish.

**Comment by mvdkleijn** [comment]
Closing as this is erroneously marked as enhanced. No actual implementation.

**Pull request closed without merging**
