### PR TITLE
New logo for changedetection.io

### PR DESCRIPTION
**Pull request by x0tester0x**

### CODE REVIEW

**Comment by x0tester0x** [comment]
Why is the new image not visible on the website [https://apps.heimdall.site/applications/foundation](https://apps.heimdall.site/applications/foundation)?

**Comment by keriati** [comment]
I guess it's a bug. In Heimdall I can already see the updated icon.

**Comment by x0tester0x** [comment]
OK, but also in Heimdall when i save the change, the new logo will not appear.

**Comment by keriati** [comment]
To update the Icon, I recommend to do an application list update and then remove and add the app again. Usually this triggers an automatic app update.

**Comment by x0tester0x** [comment]
I tried that already... nothing changes

**Pull request merged**
