### PR TITLE
Fix Unifi data retrieval

### LINKED ISSUE #626: UniFi Network Application API
Hello, the current UniFi code doesn't work well with UniFi Network Application due to specific differences in it's API:
the login route must use: `/api/login` (not /api/auth/login).  The health route must use: `/api/s/default/stat/health` (not /proxy/network).  There is no data for wan availability or lan availability on the health route (at least for my use case, I'm running the Network Application within an LXC container under proxmox).  I found "uptime" available  from route: `/api/s/default/stat/sysinfo`.  I'm running UniFi Network Application ver 7.3.83 under linux (LXC).

### PR DESCRIPTION
**Pull request by igorkulman**
Fixes #626 and #640

### CODE REVIEW

**Comment by keriati** [comment]
@igorkulman which device did you test this changes with? The current implementation works with the Dream Router without issues, so this changes would then break it for the dream router.

**Comment by igorkulman** [comment]
> @igorkulman which device did you test this changes with? The current implementation works with the Dream Router without issues, so this changes would then break it for the dream router.

I made this change to make it work with Unifi controller running in docker that I used at that time.

**Comment by mvdkleijn** [comment]
Based on comments underneath, this PR probably still needs some work. It seems that (unfortunately) the various Unifi products have differing APIs?

Comments:
- https://github.com/linuxserver/Heimdall-Apps/issues/626#issuecomment-1651238728
- https://github.com/linuxserver/Heimdall-Apps/issues/626#issuecomment-1802963385

**Comment by igorkulman** [comment]
Closing this PR as I will not continue working on it, I flashed my Unifi AP to OpenWRT so I no longer need any Unifi controller.

**Pull request closed without merging**
