### PR TITLE
Add Scrypted foundation app

### PR DESCRIPTION
**Pull request by xyzrandoxyz**

### CODE REVIEW

**Comment by Rygle** [comment]
Icons in the correct format.

Scrypted 256x256 tinypng
scrypted

**Review by mvdkleijn — CHANGES_REQUESTED** [review]
Welcome. I'm a new maintainer and looking through old PRs.

This PR is missing icons, please add some whilst keeping in mind the [image requirements](https://github.com/linuxserver/Heimdall-Apps/wiki/Image-requirements)

**Comment by mvdkleijn** [comment]
@keriati I don't suppose you remember why you labeled this PR with "bug"?

**Comment by mvdkleijn** [comment]
No response in the past 14 days and this is older than six months. Closing to try and keep things organized.

Feel free to re-open / comment when applicable.

Also:

- No icons
- Two different apps in one PR
- Enhanced app not actually implemented

**Pull request closed without merging**
