### PR TITLE
Update Proxmox to enhanced app

### PR DESCRIPTION
**Pull request by jhollowe**
* Uses API Tokens for better access control and session management
* Supports clusters of nodes
  * if no nodes specified, all clustered nodes are used
  * if listed as CSV, specific nodes are used
  * VM and LXC counts are total, memory and CPU percentages are of the entire cluster's resources

chrome_VA22Nca6jH

### CODE REVIEW

**Comment by DavidBrogli** [comment]
The memory count is not correct..
Correct calculation is: 
`'memory_percent' => (100/$memory_total)* $memory_used,`

**Comment by dgibbs64** [comment]
Tested this however it failed to load. Was able to test the api token and that worked. However, it failed when on the dashboard. sadly I can't see much apart from "server error"

image

image

**Comment by dgibbs64** [comment]
```[2022-03-19 23:23:06] local.ERROR: Trying to get property 'cpu' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'cpu' of non-object at /config/www/SupportedApps/Proxmox/Proxmox.php:55)
[stacktrace]```

**Comment by jhollowe** [comment]
@dgibbs64 what permissions does your API Token have? I think this is an issue with missing permissions and thus the returned data is an error instead of the expected data.

It minimally needs `Sys.Audit` on `/nodes` to be able to get the needed data.

**Comment by dgibbs64** [comment]
Got it working had to untick "Privilege Separation"
image

**Comment by dgibbs64** [comment]
I can see you added a note (thanks). Is it worth adding a bit about "Privilege Separation" as it may be useful for someone (like me) who knows little about api permmissions?

**Pull request merged**
